import React, { useState, useContext, useEffect } from 'react';
import axios from 'axios';
import { AuthContext } from '../../context/AuthContext';
import { createPortal } from 'react-dom';
import {
    FiDollarSign, FiUploadCloud, FiFileText, FiCheckCircle, FiX,
    FiExternalLink, FiCamera, FiTarget, FiBookOpen, FiUser, FiPhone, FiMail,
    FiHeart, FiCopy, FiGlobe, FiPlus, FiTrash2, FiLock, FiCheck, FiMapPin
} from 'react-icons/fi';

// --- Helpers ---
const buildWhatsAppText = (client) => {
    const sep = '─────────────────────';
    const paid = client.financials?.amountPaid || 0;
    const total = client.financials?.totalAgreedAmount || 0;
    const due = total - paid;
    let text = `*JCS STUDENT PROFILE*\n${sep}\n`;
    text += `👤 *Name:* ${client.name}\n`;
    text += `📞 *Phone:* ${client.phone}\n`;
    text += `🎓 *Admission Stage:* ${client.admissionStatus || 'COLLEGE FORM APPLIED'}\n`;
    if (client.guardianDetails?.name) {
        text += `\n${sep}\n👨‍👩‍👦 *Guardian Details*\n`;
        text += `• Name: ${client.guardianDetails.name}\n`;
        if (client.guardianDetails.phone) text += `• Phone: ${client.guardianDetails.phone}\n`;
    }
    text += `\n${sep}\n💰 *Financials*\n`;
    text += `• Total Fee: ₹${total.toLocaleString('en-IN')}\n`;
    text += `• Paid: ₹${paid.toLocaleString('en-IN')}\n`;
    text += `• Due: ₹${due.toLocaleString('en-IN')}\n`;
    text += `\n${sep}\n_Generated by JCS CRM_`;
    return text;
};

const WhatsAppIcon = ({ size = 14 }) => (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor">
        <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" />
    </svg>
);

const STATUS_CONFIG = {
    'COLLEGE FORM APPLIED': { dot: 'bg-purple-400', pill: 'bg-purple-50 text-purple-700 border-purple-200' },
    'WAITING FOR ALLOTMENT': { dot: 'bg-blue-400', pill: 'bg-blue-50 text-blue-700 border-blue-200' },
    'SEAT CONFIRMED': { dot: 'bg-emerald-400', pill: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
    'PAYMENT': { dot: 'bg-rose-400', pill: 'bg-rose-50 text-rose-700 border-rose-200' },
};

// --- UI Components ---
const FieldRow = ({ label, children }) => (
    <div className="flex flex-col gap-1.5">
        <label className="text-[10px] font-black text-gray-400 uppercase tracking-widest">{label}</label>
        {children}
    </div>
);

const SaveBtn = ({ onClick }) => (
    <button onClick={onClick} className="h-9 px-4 rounded-xl bg-gray-900 text-white text-[10px] font-black uppercase tracking-wider hover:bg-jcs-brand transition-colors">Save</button>
);

const CustomerDashboard = ({ client, onClose, refreshClients }) => {
    const { user } = useContext(AuthContext);

    const [uploadingDoc, setUploadingDoc] = useState(false);
    const [customDocName, setCustomDocName] = useState('');
    const [copied, setCopied] = useState(false);
    const [activeTab, setActiveTab] = useState('profile');

    const [editFinancials, setEditFinancials] = useState({ totalAgreedAmount: 0, amountPaid: 0 });
    const [editColleges, setEditColleges] = useState('');
    const [editCourse, setEditCourse] = useState('');
    const [admissionStatus, setAdmissionStatus] = useState('');
    const [editBloodGroup, setEditBloodGroup] = useState('');
    const [editAddress, setEditAddress] = useState('');
    const [editGuardian, setEditGuardian] = useState({ name: '', phone: '', email: '' });

    const [universityAccounts, setUniversityAccounts] = useState([]);
    const [newAccount, setNewAccount] = useState({ universityName: '', portalUrl: '', username: '', password: '', notes: '' });
    const [addingAccount, setAddingAccount] = useState(false);
    const [showPasswords, setShowPasswords] = useState({});

    useEffect(() => {
        if (client) {
            setEditFinancials({ totalAgreedAmount: client.financials?.totalAgreedAmount || 0, amountPaid: client.financials?.amountPaid || 0 });
            setEditColleges(client.targetColleges?.join(', ') || '');
            setEditCourse(client.targetCourse || '');
            setAdmissionStatus(client.admissionStatus || 'COLLEGE FORM APPLIED');
            setEditBloodGroup(client.bloodGroup || '');
            setEditAddress(client.address || '');
            setEditGuardian({ name: client.guardianDetails?.name || '', phone: client.guardianDetails?.phone || '', email: client.guardianDetails?.email || '' });
            setUniversityAccounts(client.universityAccounts || []);
        }
    }, [client]);

    const saveClientDetails = async (updates, silent = false) => {
        try {
            await axios.put(`/api/clients/${client._id}`, updates, { withCredentials: true });
            refreshClients();
            if (!silent) alert('Profile updated successfully!');
        } catch {
            alert('Failed to update profile.');
        }
    };

    const handleFileUpload = async (e, docType, isProfilePic = false) => {
        const file = e.target.files[0];
        if (!file) return;
        const formData = new FormData();
        formData.append('document', file);
        setUploadingDoc(true);
        try {
            const res = await axios.post('/api/upload', formData, { withCredentials: true });
            if (isProfilePic) {
                await saveClientDetails({ profilePhoto: res.data.url }, true);
            } else {
                const finalName = docType === 'Custom' ? customDocName : docType;
                const newDoc = { docType: finalName, url: res.data.url, public_id: res.data.public_id };
                await saveClientDetails({ documents: [...(client.documents || []), newDoc] }, true);
                setCustomDocName('');
            }
        } catch { alert('Upload failed.'); } finally { setUploadingDoc(false); }
    };

    const admStyle = STATUS_CONFIG[admissionStatus] || STATUS_CONFIG['COLLEGE FORM APPLIED'];

    const dashboardContent = (
        <div className="fixed inset-0 z-[9999] bg-gray-900/60 backdrop-blur-sm flex items-end sm:items-center justify-center p-0 sm:p-6">
            <div className="bg-white w-full sm:max-w-6xl h-[90vh] rounded-t-[2rem] sm:rounded-[2rem] shadow-2xl flex flex-col border border-gray-200 overflow-hidden relative">

                {/* --- Header --- */}
                <div className="shrink-0 bg-white border-b border-gray-100 z-10">
                    <div className="px-6 py-4 flex items-center justify-between">
                        <div className="flex items-center gap-4">
                            <div className="relative group/avatar">
                                <div className="w-12 h-12 rounded-2xl bg-jcs-deep flex items-center justify-center text-white font-black text-xl overflow-hidden">
                                    {client.profilePhoto ? <img src={client.profilePhoto} className="w-full h-full object-cover" /> : client.name?.charAt(0)}
                                </div>
                                <label className="absolute inset-0 bg-black/40 rounded-2xl opacity-0 group-hover/avatar:opacity-100 flex items-center justify-center text-white cursor-pointer transition-opacity">
                                    <FiCamera size={14} />
                                    <input type="file" className="hidden" onChange={(e) => handleFileUpload(e, 'photo', true)} />
                                </label>
                            </div>
                            <div>
                                <h2 className="text-lg font-black text-gray-900 leading-none mb-1">{client.name}</h2>
                                <p className="text-xs font-bold text-gray-400 uppercase tracking-widest">{client.phone}</p>
                            </div>
                        </div>

                        <div className="flex items-center gap-3">
                            <button
                                onClick={() => window.open(`https://wa.me/91${client.phone.replace(/\D/g, '')}?text=${encodeURIComponent(buildWhatsAppText(client))}`)}
                                className="h-9 px-4 rounded-xl bg-emerald-500 text-white flex items-center gap-2 text-[10px] font-black uppercase tracking-wider"
                            >
                                <WhatsAppIcon /> WhatsApp
                            </button>
                            <button onClick={onClose} className="w-9 h-9 rounded-xl bg-gray-100 flex items-center justify-center text-gray-500 hover:bg-gray-200">
                                <FiX size={18} />
                            </button>
                        </div>
                    </div>

                    <div className="px-6 flex gap-6">
                        {['profile', 'documents', 'university'].map(tab => (
                            <button
                                key={tab}
                                onClick={() => setActiveTab(tab)}
                                className={`pb-3 text-[10px] font-black uppercase tracking-[0.2em] transition-all border-b-2 ${activeTab === tab ? 'border-jcs-brand text-jcs-deep' : 'border-transparent text-gray-400 hover:text-gray-600'}`}
                            >
                                {tab}
                            </button>
                        ))}
                    </div>
                </div>

                {/* --- Body --- */}
                <div className="flex-1 overflow-y-auto bg-gray-50/50 p-6">
                    {activeTab === 'profile' && (
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                            <div className="md:col-span-2 space-y-6">
                                <section className="bg-white p-6 rounded-[2rem] border border-gray-100 shadow-sm grid grid-cols-2 gap-6">
                                    <FieldRow label="Target Course">
                                        <input value={editCourse} onChange={e => setEditCourse(e.target.value)} className="w-full bg-gray-50 border-none rounded-xl px-4 py-2 text-sm font-bold focus:ring-2 ring-jcs-brand/20" />
                                    </FieldRow>
                                    <FieldRow label="Target Colleges">
                                        <input value={editColleges} onChange={e => setEditColleges(e.target.value)} className="w-full bg-gray-50 border-none rounded-xl px-4 py-2 text-sm font-bold" />
                                    </FieldRow>
                                    <div className="col-span-2 flex justify-end">
                                        <SaveBtn onClick={() => saveClientDetails({ targetCourse: editCourse, targetColleges: editColleges.split(',').map(s => s.trim()) })} />
                                    </div>
                                </section>

                                <section className="bg-white p-6 rounded-[2rem] border border-gray-100 shadow-sm grid grid-cols-2 gap-6">
                                    <h3 className="col-span-2 text-[10px] font-black text-gray-400 uppercase tracking-widest border-b pb-2">Guardian Information</h3>
                                    <FieldRow label="Name">
                                        <input value={editGuardian.name} onChange={e => setEditGuardian({ ...editGuardian, name: e.target.value })} className="w-full bg-gray-50 border-none rounded-xl px-4 py-2 text-sm font-bold" />
                                    </FieldRow>
                                    <FieldRow label="Phone">
                                        <input value={editGuardian.phone} onChange={e => setEditGuardian({ ...editGuardian, phone: e.target.value })} className="w-full bg-gray-50 border-none rounded-xl px-4 py-2 text-sm font-bold" />
                                    </FieldRow>
                                    <div className="col-span-2 flex justify-end">
                                        <SaveBtn onClick={() => saveClientDetails({ guardianDetails: editGuardian })} />
                                    </div>
                                </section>
                            </div>

                            <div className="space-y-6">
                                <div className="bg-jcs-deep text-white p-6 rounded-[2rem] shadow-xl">
                                    <div className="flex justify-between items-start mb-6">
                                        <FiDollarSign className="text-jcs-brand" size={24} />
                                        <div className="text-right">
                                            <p className="text-[10px] font-black uppercase opacity-60">Total Due</p>
                                            <p className="text-2xl font-black">₹{(editFinancials.totalAgreedAmount - editFinancials.amountPaid).toLocaleString()}</p>
                                        </div>
                                    </div>
                                    <div className="space-y-4">
                                        <FieldRow label="Total Amount">
                                            <input type="number" value={editFinancials.totalAgreedAmount} onChange={e => setEditFinancials({ ...editFinancials, totalAgreedAmount: Number(e.target.value) })} className="w-full bg-white/10 border-none rounded-xl px-4 py-2 text-sm font-bold" />
                                        </FieldRow>
                                        <FieldRow label="Paid">
                                            <input type="number" value={editFinancials.amountPaid} onChange={e => setEditFinancials({ ...editFinancials, amountPaid: Number(e.target.value) })} className="w-full bg-white/10 border-none rounded-xl px-4 py-2 text-sm font-bold" />
                                        </FieldRow>
                                        <button onClick={() => saveClientDetails({ financials: editFinancials })} className="w-full py-3 bg-jcs-brand text-jcs-deep font-black rounded-xl text-xs uppercase tracking-widest">Update Payment</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}

                    {activeTab === 'documents' && (
                        <div className="bg-white rounded-[2rem] p-8 border border-gray-100">
                            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                                {client.documents?.map((doc, i) => (
                                    <a key={i} href={doc.url} target="_blank" rel="noreferrer" className="group p-4 bg-gray-50 rounded-2xl border border-dashed border-gray-200 hover:border-jcs-brand transition-all flex flex-col items-center text-center">
                                        <FiFileText size={24} className="text-gray-400 group-hover:text-jcs-brand mb-2" />
                                        <span className="text-[10px] font-black uppercase truncate w-full">{doc.docType}</span>
                                    </a>
                                ))}
                                <label className="p-4 bg-gray-50 rounded-2xl border border-dashed border-gray-300 flex flex-col items-center justify-center cursor-pointer hover:bg-gray-100">
                                    <FiPlus size={24} className="text-gray-400" />
                                    <span className="text-[10px] font-black uppercase mt-2">Add Doc</span>
                                    <input type="file" className="hidden" onChange={(e) => handleFileUpload(e, 'Document')} />
                                </label>
                            </div>
                        </div>
                    )}

                    {activeTab === 'university' && (
                        <div className="space-y-4">
                            {universityAccounts.map((acc, i) => (
                                <div key={i} className="bg-white p-6 rounded-[2rem] border border-gray-100 flex items-center justify-between">
                                    <div className="flex items-center gap-6">
                                        <div className="w-12 h-12 bg-blue-50 text-blue-600 rounded-2xl flex items-center justify-center font-black uppercase text-xs">{acc.universityName.charAt(0)}</div>
                                        <div>
                                            <p className="font-black text-gray-900">{acc.universityName}</p>
                                            <p className="text-xs font-bold text-gray-400">{acc.username}</p>
                                        </div>
                                    </div>
                                    <div className="flex items-center gap-2">
                                        <button onClick={() => { navigator.clipboard.writeText(acc.password); alert('Password Copied'); }} className="p-2 hover:bg-gray-100 rounded-lg"><FiCopy size={14} /></button>
                                        <button onClick={() => handleDeleteUniversityAccount(i)} className="p-2 hover:bg-red-50 text-red-500 rounded-lg"><FiTrash2 size={14} /></button>
                                        {acc.portalUrl && <a href={acc.portalUrl} target="_blank" rel="noreferrer" className="h-8 px-4 bg-gray-900 text-white rounded-lg flex items-center text-[10px] font-black uppercase tracking-widest">Login</a>}
                                    </div>
                                </div>
                            ))}
                            <button onClick={() => setAddingAccount(true)} className="w-full py-4 border-2 border-dashed border-gray-200 rounded-[2rem] text-gray-400 font-black text-[10px] uppercase tracking-widest hover:border-jcs-brand hover:text-jcs-brand transition-all">+ Add University Portal</button>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );

    return createPortal(dashboardContent, document.body);
};

export default CustomerDashboard;